language: go
sudo: false
install: false

before_install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls

script:
- make

after_success:
- echo "Build Successful!" 
after_failure:
- echo "Build Failed!" 

