language: go
sudo: false
install:
- go get -t 
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls

script:
- PATH="$HOME/gopath/bin:$PATH"
- hack/coverage

after_success:
- echo "Build Successful!" 
after_failure:
- echo "Build Failed!" 

